# Generated by Django 6.0.3 on 2026-03-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.asignacion', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.asignacion', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='usuarios.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'año_escolar')},
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='entregaactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.actividad', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='entregaactividad',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuarios.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='nota',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.asignacion', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('asignacion', 'estudiante', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='entregaactividad',
            unique_together={('actividad', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('curso', 'materia', 'profesor', 'año_escolar')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('asignacion', 'estudiante', 'periodo')},
        ),
    ]
