# Generated by Django 6.0.3 on 2026-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_codigoactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('cambio_requerido', 'Cambio de contraseña requerido'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_temp_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración contraseña temporal'),
        ),
    ]
